### ISSUE TITLE
Magento 2.3 Zend_Application_Resource_Mail not found

### ISSUE THREAD

**Issue by robertkent** [mageplaza/magento-2-smtp#127]
As per #118 - looks like the Zend Application folder is no longer included in Magento 2.3

**Comment by Arthas78** [comment]
2 days ago, Magento updated to version 2.3, I checked in there and saw some classes in which they left so the problem appears. The current SMTP module is not yet compatible with version 2.3. We are still looking for a solution to update it

**Comment by n2diving-dgx** [comment]
Class 'Zend_Application_Resource_Mail' not found on fresh install of M 2.3

**Comment by Arthas78** [comment]
Yes, They have removed the entire zend/application folder

**Comment by poveu** [comment]
Hello, is there any estimated time of fixing this? Module SocialLogin depends on Smtp module so they both are incomaptible with Magento 2.3

**Comment by Arthas78** [comment]
We haven't yet been able to determine the specific time needed to upgrade, as this is a big update to Magento.
So that please don't rush to upgrade to 2.3 version. We're afraid of some odd error will occur

**Comment by koopjesboom** [comment]
This is a real big problem because even if you remove the extension the compiler stays broken.
There were enough beta versions of magento 2.3 to test all the extensions for a long time so I don't understand why the extensions are not ready. Because Porto theme uses also Mageplaza extensions and they claim to be ready  for version 2.3

This can not be repaired the easy way. 

I removed the Smtp module extension but no luck because of Porto theme has also extensions from Mageplaza including the Mageplaza core extension. The problem now is that the compiler is broken, and static contend can not be deployed. These actions give errors. So it would be nice to tell the people what to do if they updated already to version 2.3 The only thing i can do is restore a backup I made before the update. Even Porto theme is claiming they are 2.3 ready I don't think it is working out of the box.

So be warned do not update Magento to version 2.3 if you use Mageplaza extensions or Porto theme until further notice.

**Comment by poveu** [comment]
Porto support is a mess, so don't expect anything great about it. I'm using their theme too and I always face issues with their updates) and with every update I have to patch some of modules/blocks etc... I got used to it. 

Anyway, you can't blame Mageplaza team for that, especially when they offer this extension for free. Just don't use 2.3 until all your modules (including Mageplaza ones) are really 2.3-ready.

**Comment by koopjesboom** [comment]
Yes i agree on the Porto part. This should never be allowed and sold on envato market.

**Comment by deanpeterson** [comment]
So what is the estimated time to fix this? I recently wrote a review praising mageplaza for their quality wishing they would do larger extensions for magento. But this has pretty much made me do a 180. I only use this SMTP extension and their Google Tag Manager extension. I need to upgrade to 2.3 for some of their bug fixes and features in other areas. I'm not too heavily invested in mageplaza, if this is going to take even a few more days I'm inclined to just drop the core of mageplaza and both extensions and find replacements.

**Comment by Lordfef** [comment]
OH my God!
I install Mageplaza SMTP extension to set my personal smtp account and now I can't send any mail :(
Any other solution while this fix go online?
Thank's

**Comment by codemastering** [comment]
We are having same issue here as well.

How long will this issue fix?  We really need to upgrade to M2.3

Please reply soonest so we can may be shift our smtp with any other compatible module if you might take long time to fix this issue.

Waiting for your soonest response.

Thank you

**Comment by Arthas78** [comment]
Hi boys,
We are still looking for a solution so that SMTP module can run stably in Magento versions. Currently, we are having trouble with message handling on 2.3. It implements from a new interface that Magento 2.3 has just added. So we need more time to address these issues.
Please kindly understand!

**Comment by woshka** [comment]
hello,
how to remove mageplaza smtp social login and core extension to have the compiler recompile without issues till the extenssion upgrade?

Thanks

**Comment by codemastering** [comment]
> Hi boys,
> We are still looking for a solution so that SMTP module can run stably in Magento versions. Currently, we are having trouble with message handling on 2.3. It implements from a new interface that Magento 2.3 has just added. So we need more time to address these issues.
> Please kindly understand!

please advise how we can remove the plugin because at the moment when we remove the module than it shows below error at compilation

In ClassReader.php line 35:

  Class Magento\Email\Model\Source\Variables does not exist

In ClassReader.php line 29:

  Class Magento\Email\Model\Source\Variables does not exist


Please reply soonest possible

Thank you

**Comment by codemastering** [comment]
> I found the resolution to this issue
> after that I we should ran the
> composer update
> and it will be finally completely be removed from the server
> 
> Thanks

thank you for letting us know.

Please compile and see if its compiling or giving below error after remove this plugin.

**In ClassReader.php line 35:

Class Magento\Email\Model\Source\Variables does not exist

In ClassReader.php line 29:

Class Magento\Email\Model\Source\Variables does not exist**

**Comment by woshka** [comment]
I compiled and there are no errors after removing it with that method

**Comment by woshka** [comment]
I compiled and there are no errors after removing it with that method

**Comment by Arthas78** [comment]
yes @woshka you can remove by composer command. You can refer the link 
https://github.com/mageplaza/module-core/issues/3

**Comment by codemastering** [comment]
> I compiled and there are no errors after removing it with that method
We are still getting below error even after running composer update

In ClassReader.php line 35:

Class Magento\Email\Model\Source\Variables does not exist

In ClassReader.php line 29:

Class Magento\Email\Model\Source\Variables does not exist

> yes @woshka you can remove by composer command. You can refer the link
> [mageplaza/module-core#3](https://github.com/mageplaza/module-core/issues/3)

This method is not working as well.

Please guide how we can remove this smtp module and compile successfully without getting below error.

In ClassReader.php line 35:

Class Magento\Email\Model\Source\Variables does not exist

In ClassReader.php line 29:

Class Magento\Email\Model\Source\Variables does not exist

@Arthas78 Please guide how we can remove smtp module OR Please advise if you are going to fix and release the latest version of smtp module by this weekend?? We really want to update to Magento 2.3 soonest. Please reply soon. thank you

**Comment by Kgroop** [comment]
HI @Arthas78 do you have an update?

**Comment by Arthas78** [comment]
@Kgroop We are still reading to find out the running stream of Magento 2.3
@codemastering Did you run the composer update command? I saw @woshka ran it and he succeeded

**Comment by codemastering** [comment]
@Arthas78 yes i tried running composer update but its still giving me same issue as below.

In ClassReader.php line 35:

Class Magento\Email\Model\Source\Variables does not exist

In ClassReader.php line 29:

Class Magento\Email\Model\Source\Variables does not exist


Please advise how i can get rid off this smtp module and compile successfully??

Thank you

**Comment by woshka** [comment]
> @Arthas78 yes i tried running composer update but its still giving me same issue as below.
> 
> In ClassReader.php line 35:
> 
> Class Magento\Email\Model\Source\Variables does not exist
> 
> In ClassReader.php line 29:
> 
> Class Magento\Email\Model\Source\Variables does not exist
> 
> Please advise how i can get rid off this smtp module and compile successfully??
> 
> Thank you

check if there are any modules in your app/code or app/design that are having di.xml that causes some issues
you can removing all content from app/code and app/design to see if the problem will be solved

after that if that didn;t solve the issue try replacing all the files with a fresh 2.3.0 by unziping it on the same directory

if you have manually removed them by composer try reinstalling them and them removing them by magento module manager uninstaller in the bin directory and then run composer update on the root of your website

**Comment by codemastering** [comment]
@woshka thank you so much for the advise. let me try soonest now. will get back in few moments. thank you

**Comment by codemastering** [comment]
@woshka after removing all content from app/code and app/design  the compilation has been successful

What could be the problem ?

**Comment by woshka** [comment]
technical instructions is that there seems to be an issue with one of your modules having a plugin inside it overriding one of magento's core functionality
with magento 2.3.0 there has been some changes maybe the core function name chaned or removed etc
try copying all the plugins one after the other
after each copy run setup:upgrade and run ./magento again to see which plugin(s) is causing the issue
after that try analyzing it that which one is overriding the core functionality and fix it or use another plugin instead

**Comment by codemastering** [comment]
@woshka thank you so much. the issue resolved. there was another module in which the issue arises. I think Magento 2.3 is not worthy for upgrade at the moment as many existing modules are not ready to be migrate to Magento 2.3

Lets stick with where we are right now.

Magento 2.3 is now the story of next 1-2 months hopefully.

Thank you so much @woshka

**Comment by woshka** [comment]
glad to see your issue has been resolved
yes unfortunately magento 2.3.0 isn't still fully tested and has some minor bugs too
one fo them is addressed here
https://github.com/magento/magento2/issues/19549

however if the only huge bug is the one above and only having issue with this smtp
its better to update and use another magento 2.3.0 ready smtp extenssions

also in my opinion there should be a built in smtp with magento 2 like it was before in 1.x versions

**Comment by codemastering** [comment]
@woshka  you are right. Magento 2 should have its integrated SMTP Module.

I searched a lot but still unable to find Magento 2.3 ready smtp extension for free, please share if you find any?

another module which is giving us issue is for the Invoice Pdf generator and the make of the module assured us that they will be releasing the fix for this issue by next week.

I think its better to wait till Magento 2.3.1 releases.

It will be too early to upgrade for now :(

**Comment by woshka** [comment]
I just know some that are not for free and are working with magento 2.3.0
and their price are not so much

**Comment by codemastering** [comment]
@woshka alright. Please share.

**Comment by koopjesboom** [comment]
For the information:

Magento 2.3
Mageplaza SMTP version 1.2.6 with error's

/public_html/error_log

[12-Dec-2018 11:01:49 UTC] PHP Fatal error:  Class 'Zend_Application_Resource_Mail' not found in /home/my_username/public_html/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php on line 31

Beste regards

**Comment by gntlby** [comment]
How long will this issue fix?
Thanks.

**Comment by gntlby** [comment]
How long will this issue fix?
Thanks.

**Comment by codemastering** [comment]
> How long will this issue fix?
> Thanks.

seems like mageplaza is still working on this issue or maybe they are delaying because they need more time to understand this issue.

It will be better to move to other smtp solutions rather than waiting for the fix.

**Comment by Arthas78** [comment]
@gntlby Now, I have sent the mail but still have some problems showing up in the email log so I think the SMTP update will soon complete.

**Comment by Arthas78** [comment]
@panteliskopsias We are testing and also have some problems with sending mail of the checkout page. We are trying to find a solution for it

**Comment by tejashp77** [comment]
This issue is fixed or not?

**Comment by pattu310vimir** [comment]
The issue remains or solved?

**Comment by Arthas78** [comment]
@pattu310vimir We have completed the patch and are testing it on our site

**Comment by michelecanal** [comment]
Excellent! We are waiting for it

Il giorno Ven 28 Dic 2018, 11:05 Arthas78 <notifications@github.com> ha
scritto:

**Comment by codemastering** [comment]
no update as yet

**Comment by Arthas78** [comment]
@codemastering We just finished the holiday season. If you want to create a ticket, I will send you a patch
https://www.mageplaza.com/contact.html

**Comment by codemastering** [comment]
@Arthas78 thank you for the reply.

Unfortunately we are now using another plugin which is working perfectly for our needs.

You might lose 1 free user ;)  LOL Just jokin. plz don't mind...

Still looking forward to see your next update for the smtp plugin. lets see how it goes. Best of Luck! & Happy Coding! ;)

**Comment by panteliskopsias** [comment]
Happy new year! How you go with the proccess? Do you know when we waiting the new version of smtp?

**Comment by koopjesboom** [comment]
@codemastering 

Can you share the name of the plugin.

I have used the patch provided by Mageplaza but i have still the same issues compiling.

php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [==>-----------------]  14% < 1 sec 66.5 MiB
Fatal error: Class 'Zend_Application_Resource_Mail' not found in my_server/me_the_user/public_html/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php on line 31

Happy new year

**Comment by codemastering** [comment]
@koopjesboom  i am not using Mageplaza any more now.

**Comment by koopjesboom** [comment]
@codemastering 

What are you using?

Best regards

**Comment by waldok** [comment]
But this SMTP extension doesn't have sent mail log or does it?

**Comment by codemastering** [comment]
@waldok Yes but we don't need mail log because we take logs from our mail server itself. if anyone don't want mail log than i suggest to use Magepals, its very good plugin 👍

**Comment by koopjesboom** [comment]
When i removed the Mageplaza SMTP extension my database is broken.
 
I can not run  : php bin/magento setup:upgrade 
Installing schema... Upgrading schema... SQLSTATE[42S21]: Column already exists:      Duplicate column name 'sender'

![sqlstate 1060](https://user-images.githubusercontent.com/15247780/50644722-f5bc7300-0f71-11e9-903a-46f7fbf79882.png)

Has anyone a solution for this problem?

**Comment by Arthas78** [comment]
@koopjesboom I think you are using composer to install our SMTP module. It looks like you have installed incorrectly. In the patch I sent to you, I started from app / code (since I installed the module manually). If you install by composer download the file and replace it with the vendor/Mageplaza/ module_smtp path.
Example: File app/code/Mageplaza/Smtp/Mail/Transport.php will be replaced for the file vendor/Mageplaza/module_smtp/Mail/Transport.php

**Comment by datasolution75** [comment]
Hello, are you planning to release a fix anytime soon about this ? Is the patch available anywhere ?

**Comment by tarikuli** [comment]
Hi Guys 
Any good luck? Find any solution?
 
PHP Fatal error:  Class 'Zend_Application_Resource_Mail' not found in /vendor/mageplaza/module-smtp/Mail/Rse/Mail.php on line 31

**Comment by Arthas78** [comment]
Hi @datasolution75  If you really need it, please contact us here. I will send a patch link for you
https://www.mageplaza.com/contact.html

**Comment by lracicot** [comment]
This is a real blocker. Any ETA on it?

**Comment by koopjesboom** [comment]
@Arthas78 

Why isn't it possible to update the download package and the composer package with this patch/fix?

This make me and other users of the free extension so frustrated and in the end will not result in buying your extensions or get interested in your extensions any more.

If you provide a free extension it is great,  thank you very much for this.
If you provide something no one can use because it is to difficult to maintain and to difficult to get it running it is better to take it completely offline until the extension runs out of the box.
I think people underestimate how many people are depending on extensions like this to keep their shop running well.

In the end i think this is very bad advertising for Mageplaza.
Why isn't it possible to update the download package and the composer package with this patch/fix?

I uploaded all the files to the right folders, do not install the module Mageplaza SMTP with composer.
It is not working.

I am going to try manual installation.

**Comment by koopjesboom** [comment]
@Arthas78 

Manual installation gives the same result with patch included:

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'sender'
[kboom@mp28 public_html]$ php bin/magento setup:upgrade SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'sender'

**Comment by codemastering** [comment]
@koopjesboom 

MagePlaza is not a company in which i will invest at all for my plugins requirements. They are not good in providing support and unresponsive.

**Comment by koopjesboom** [comment]
@codemastering 

Best,

This is why i asked the question: Why isn't it possible to update the download package and the composer package with this patch/fix?

This is 10 minutes work for them, and will keep people satisfied which results in sales and income for there products in the end.

But if you have a suggestion how to resolve this issue?
If this extension is working it is a great extension.

Best regards

**Comment by codemastering** [comment]
@koopjesboom 

unfortunately, i don't have any solution but you have other choices as well like swissup smtp or magepal smtp. they are for free!  and works GREAT!!!

**Comment by codemastering** [comment]
@koopjesboom 

forget mageplaza, they are sick. if tomorrow magento 2.4 releases and same issue comes up. your clients will be pissed! and they won't listen either you have this or that problem. they want SOLUTION!!! thats it!

**Comment by koopjesboom** [comment]
@codemastering 

Yes i am looking for an alternative module.

I am wondering why Magento decides to remove well working Magento 1 elements out of Magento 2
In Magento one mail was very easy to configure. Why change things that are working well.

But this is another discussion.

Best regards

**Comment by koopjesboom** [comment]
I was looking at the magento 2 forums on SMTP problems.
It seems to be this is the most used Extension, Mageplaza SMTP to get SMTP working on Magento 2(.3)

So it is not unthinkable more than 75% of the magento users are depending on this extension.

Why if your core business is selling extensions you ar providing your free extension like this.
This reveals how they work on Mageplaza. they don't care about users and customers.
It is all about the money, just like Porto Theme they work exactly the same way.
It looks like they are the same people to me or very close related.

Mageplaza you should help the people.
You will gain profit out of this later, that is a normal reaction of good work and helping people.

**Comment by codemastering** [comment]
@koopjesboom 

i suggest you to move quickly forward and choose other plugins for smtp needs otherwise you will end up fighting with your clients.

**Comment by dmcanna** [comment]
It works for me after update on v1.2.7
Here is a commit with a fix https://github.com/mageplaza/magento-2-smtp/commit/a0922b98cc8f484b6994670938d9db2f815315e9

**Comment by Arthas78** [comment]
We have completed the update process. You can get new version SMTP here
https://github.com/mageplaza/magento-2-smtp

**Comment by blopa** [comment]
Does it still works with Magento 2.2.x?

**Comment by Arthas78** [comment]
We have just updated version 1.2.9. It runs on Magento versions 2.2.x

**Comment by gntlby** [comment]
> We have completed the update process. You can get new version SMTP here
> https://github.com/mageplaza/magento-2-smtp

When run this command: bin/magento setup:di:compile

Repositories code generation... 1/7 [==>-----------------]  14% < 1 sec 48.0 MiBPHP Fatal error:  Class 'Zend_Application_Resource_Mail' not found in /var/www/html/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php on line 31

Have a any idea?
Thanks.

<img width="579" alt="ekran resmi 2019-01-16 20 35 20" src="https://user-images.githubusercontent.com/45899771/51267254-56b26500-19ce-11e9-9dea-b7e56d539020.png">

**Comment by lracicot** [comment]
@gntlby are you sure you have the latest version installed? Check your composer.lock for
```
"name": "mageplaza/module-smtp",
"version": "1.2.9",
```

**Comment by gntlby** [comment]
> @gntlby are you sure you have the latest version installed? Check your composer.lock for
> 
> ```
> "name": "mageplaza/module-smtp",
> "version": "1.2.9",
> ```

When I run this command: composer require mageplaza/module-smtp
Using version ^1.2 for mageplaza/module-smtp ./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing mageplaza/module-smtp (1.2.0): Loading from cache
Writing lock file
Generating autoload files
So installing 1.2.0 version not 1.2.9.

How can I get latest version with composer? 
Thanks.

**Comment by Arthas78** [comment]
We have released a new version 1.2.9 so I will close this issue here. This is a link
https://github.com/mageplaza/magento-2-smtp

**Comment by Arthas78** [comment]
This new SMTP version 1.2.9 is compatible with the Magento version 2.3

**Comment by saxsax1995** [comment]
Some how, if you remove and then require the smtp again, and it doesn't fix the problem, here is some thing else you should try:
Go to your database (Mysql or something), then find table name "mageplaza", then drop that table, then run setup:upgrade again.
That worked for me. Hope its help some one.
