### ISSUE TITLE
SMTP error in Magento CE 2.3.3

### ISSUE THREAD

**Issue by michelecanal** [mageplaza/magento-2-smtp#199]
Hi, 
I'm testing the upgrade from Magento CE 2.3.2 to 2.3.3. 

I think that Magento change again something. 
Can you check, please? 
Thanks! 

main.CRITICAL: Invalid header value detected {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Invalid header value detected at /home/[...]/vendor/mageplaza/module-smtp/Mail/Transport.php:118, Zend\\Mail\\Header\\Exception\\RuntimeException(code: 0): Invalid header value detected at /home/[...]/vendor/zendframework/zend-mail/src/Header/HeaderValue.php:112)"}

**Comment by bartoll** [comment]
Hi,
I can confirm that after upgrading Magento to 2.3.3, something has broken. My Magento has stopped sending emails, too.

**Comment by Arthas7895** [comment]
Thank you for your announcement, Magento version 2.3.3 has just been released yesterday so we are installing it and will check this module again.

**Comment by michelecanal** [comment]
Hi, it's not a mageplaza SMTP problem but a Magento 2.3.3 issue.
The problem is special characters (as "à") in sender name.
Thanks to Mageplaza for finding the issue

**Comment by bartoll** [comment]
@michelecanal Do you have solution that fixes this problem?

**Comment by michelecanal** [comment]
No at the moment
But you can temporary substitute special characters

for magento issue look at https://github.com/magento/magento2/issues/24957



Il giorno gio 10 ott 2019 alle ore 12:48 bartoll <notifications@github.com>
ha scritto:

**Comment by Arthas7895** [comment]
After checking Magento version 2.3.3, it seems that I understood the problem of @michelecanal
Magento has changed, using EmailMessageInterface instead of MessageInterface like previous versions
In the EmailMessage class, they use the default encoding 'ASCII' instead of 'utf-8', which causes the test to fail. Magento may have lacked the set encoding segment when initialized because their previous versions used it|| https://prnt.sc/phpnpx
Currently, there are 2 ways to solve the 
1st that you can remove all the special characters
2nd, easiest to do, you add a code to set encoding for $message here || https://prnt.sc/phpolk
(This way is not recommended because it is fixed into the core Magento)
In addition, we will try to find another way instead. Hope this message helps you

**Comment by elvinristi** [comment]
see https://github.com/magento/magento2/issues/24902 which has fix in PR https://github.com/magento/magento2/pull/24906

**Comment by nevinsm** [comment]
@Arthas7895 
There is also an issue with using Amazon SES as the SMTP host. I now get "554 Transaction failed: Expected disposition, got =\r\n" as an error when attempting to send the test email. Would you like a new issue for that?

**Comment by elfeffe** [comment]
@Arthas7895 I have the same issue

**Comment by jihadbek** [comment]
@Arthas7895 me also getting this error with SES

**Comment by Arthas7895** [comment]
I checked with amazon SES and got the same problem. I also tried with dot-mailer and I didn't get any email. It seems that the module can't use amazon SES on 2.3.3. We are checking again and will notify when completed

**Comment by ammarabdulsalam** [comment]
I was able to make this module works again using AWS SES by removing the "Content-Disposition" from headers.
`$message->getHeaders()->removeHeader("Content-Disposition");`

in Mageplaza/Smtp/Mail/Transport.php
`before $transport->send($message);`

**Comment by elfeffe** [comment]
Which port do you use?

**Comment by ammarabdulsalam** [comment]
I'm using TLS/587 with us-east-1

**Comment by adamrandazzo** [comment]
This was posted on the Magento forums: https://community.magento.com/t5/Magento-DevBlog/Backward-incompatible-Changes-in-the-Mail-Library-for-Magento-2/ba-p/144787

**Comment by Condelab** [comment]
please how do i resolve this, 
`Fatal error: Uncaught TypeError: Argument 1 passed to Mageplaza\EmailAttachments\Model\MailEvent::dispatch() must be an instance of Mageplaza\EmailAttachments\Mail\Message, instance of Magento\Framework\Mail\EmailMessage given, called in /var/www/html/vendor/mageplaza/module-email-attachments/Mail/TransportFactory.php on line 65 and defined in /var/www/html/vendor/mageplaza/module-email-attachments/Model/MailEvent.php:102 Stack trace: #0 /var/www/html/vendor/mageplaza/module-email-attachments/Mail/TransportFactory.php(65): Mageplaza\EmailAttachments\Model\MailEvent->dispatch(Object(Magento\Framework\Mail\EmailMessage)) #1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Mageplaza\EmailAttachments\Mail\TransportFactory->aroundCreate(Object(Magento\Framework\Mail\TransportInterfaceFactory\Interceptor), Object(Closure), Array) #2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\Mail\TransportInterfaceFactory\Interceptor->Magento\Framework\Interception\{closu in /var/www/html/vendor/mageplaza/module-email-attachments/Model/MailEvent.php on line 102`

**Comment by elfeffe** [comment]
I’m using Mailgun SMTP for now, to keep working.

**Comment by Arthas7895** [comment]
@Condelab Thank you for the information, this is the problem of the email attachment module. We are testing it on 2.3.3 and will update it ASAP

**Comment by bartoll** [comment]
I am not getting order confirmation email from my magento 2.3.3,
when recipient's name includes IDN letters e.g. in "Bartłomiej".

There is something wrong in this method:

vendor/mageplaza/module-smtp/Mail/Transport.php
>     /**
>      * @param TransportInterface $subject
>      * @param \Closure $proceed
>      * @throws MailException
>      * @throws \Zend_Exception
>      */
>     public function aroundSendMessage(
>         TransportInterface $subject,
>         \Closure $proceed
>     )
>     {
>         $this->_storeId = $this->registry->registry('mp_smtp_store_id');
>         $message = $this->getMessage($subject);
>         if ($this->resourceMail->isModuleEnable($this->_storeId) && $message) {
>             if ($this->helper->versionCompare('2.3.0')) {
>                 $message = \Zend\Mail\Message::fromString($message->getRawMessage());
>             }
>             $message = $this->resourceMail->processMessage($message, $this->_storeId);
>             $transport = $this->resourceMail->getTransport($this->_storeId);
>             try {
>                 if (!$this->resourceMail->isDeveloperMode($this->_storeId)) {
>                     $transport->send($message);
>                 }
>                 $this->emailLog($message);
>             } catch (\Exception $e) {
>                 $this->emailLog($message, false);
>                 throw new MailException(new Phrase($e->getMessage()), $e);
>             }
>         } else {
>             $proceed();
>         }
>     }

Exactly in this lines:
            **if ($this->helper->versionCompare('2.3.0')) {
                 $message = \Zend\Mail\Message::fromString($message->getRawMessage());
            }**

Before this, $message object has proper encoding settings (UTF-8), and after this encoding is accidentally changed to 'ASCII'. That causes exception in next brackets.

**Comment by bartoll** [comment]
Native magento problems with proper encoding when sending emails, was solved after installation of this official patch 'EmailMessageInterface_2.3.3_backward_compatibility_composer-2019-10-14-03-43-31.patch'.
When I disabled mageplaza/smtp module, it works and I get all emails.
After enabling this module, i don't get emails with IDN letters in recpient's name.

**Comment by bartoll** [comment]
My solution that works is inserting line as below.

vendor/mageplaza/module-smtp/Mail/Rse/Mail.php:
    public function processMessage($message, $storeId)
    {
        ....

        **$message->setEncoding('UTF-8');**

        return $message;
    }

**Comment by adamrandazzo** [comment]
I was able to get 2.3.3 working on SES with the suggestions above. One thing I also noticed is that the logged emails seem malformed now (although the actual emails come through correctly).

See attached screenshot

<img width="764" alt="Screen Shot 2019-10-23 at 11 25 03 AM" src="https://user-images.githubusercontent.com/8340768/67409429-9115e780-f588-11e9-8ec1-0a7b1498d0c6.png">

Any ideas?

**Comment by bartoll** [comment]
I confirm problem with email's preview in logs grid. No idea how to fix it. Anyone?

**Comment by Arthas7895** [comment]
Please add this code in the Model / log.php file and your messages in the background will be displayed correctly || https://prnt.sc/pnc4sw
You can get code here
https://github.com/mageplaza/magento-2-smtp/blob/develop/Model/Log.php

**Comment by jihadbek** [comment]
> 
> 
> > I was able to make this module works again using AWS SES by removing the "Content-Disposition" from headers.
> > `$message->getHeaders()->removeHeader("Content-Disposition");`
> > in Mageplaza/Smtp/Mail/Transport.php
> > `before $transport->send($message);`
> 
> Thanks , done the same fix and now it is working

actually i just notice that it is not fully working , there is other issue which related to special characters ( arabic language for my case ) what happen in my case was issue when registering new clients which have arabic names , so i disable the module for now .

**Comment by bartoll** [comment]
@jihadbek check my last fix code.

**Comment by SoloDevAtrix** [comment]
I downloaded and tried the newest code from github but I get this:
Transaction failed: Domain contains illegal character

Trace it to quotable characters being in everything even headers, which makes the from address invalid:
![image](https://user-images.githubusercontent.com/47590583/67623287-92d9e800-f7e0-11e9-9a68-0da3323a8e44.png)

Log still shows bad too as you can see.

**Comment by SoloDevAtrix** [comment]
I got it to send by seeing what it sends to the smtp server and this line mixed with removing content-disposition header was my solution, but it's not fixed, just hacked.

Return-Path: =?UTF-8?Q?sales@wanaryd.com?=
Should be
Return-Path: sales@domain.com

**Comment by SoloDevAtrix** [comment]
Fatal error: Uncaught TypeError: Argument 3 passed to Magento\Framework\Mail\Template\TransportBuilder::addAddressByType() must be of the type string or null, integer given, called in /home/nginx/domains/domain.com/public/vendor/magento/framework/Mail/Template/TransportBuilder.php on line 202 and defined in /home/nginx/domains/domain.com/public/vendor/magento/framework/Mail/Template/TransportBuilder.php:420 Stack trace: #0 /home/nginx/domains
going to an email and hitting resend gives the following:
/domain.com/public/vendor/magento/framework/Mail/Template/TransportBuilder.php(202): Magento\Framework\Mail\Template\TransportBuilder->addAddressByType('to', 'hartshaulingand...', 0) #1 /home/nginx/domains/domain.com/public/generated/code/Magento/Framework/Mail/Template/TransportBuilder/Interceptor.php(37): Magento\Framework\Mail\Template\TransportBuilder->addTo('hartshaulingand...', 0) #2 /home/nginx/domains/domain.com/public/app/code/Mageplaza/Smtp/Model/Log.php(201): Magento\Framework\Mail\Template\TransportBuilder\Interceptor->addTo('hartshaulingand...', 0) #3 /home/nginx/dom in /home/nginx/domains/domain.com/public/vendor/magento/framework/Mail/Template/TransportBuilder.php on line 420

**Comment by bahramdavodi** [comment]
fixed in [#24906](https://github.com/magento/magento2/pull/24906)

**Comment by SoloDevAtrix** [comment]
As said above, my issues have nothing to do with special characters.

**Comment by Arthas7895** [comment]
My fix works only for the message created after the code has been fixed. It will not work with a previously created message. Please make sure you try a new message when changing the code
This is a result || https://prnt.sc/poym4t

**Comment by elvinristi** [comment]
Related unsolved issue reference to `Content-Disposition`:
- https://github.com/magento/magento2/issues/25076

**Comment by taoufiqaitali** [comment]
> @Arthas7895
> There is also an issue with using Amazon SES as the SMTP host. I now get "554 Transaction failed: Expected disposition, got =\r\n" as an error when attempting to send the test email. Would you like a new issue for that?

Any solution for this?! Not fixed when using latest version of module and patches

**Comment by nevinsm** [comment]
@taoufiqaitali Keep in mind that Magento 2.3.3 introduced some very unexpected breaking changes, that really messed with low level APIs in the system. You will have to have some patience while their team works it out, or you could take a stab at downloading the latest code from the repo and helping them with the fix. I can only imagine the headache Mageplaza is having allocating resources to fix all the bugs 2.3.3 likely caused across their product stack.

**Comment by SoloDevAtrix** [comment]
Warning to others, just totally disable m2 sending email till this is fixed, we were paused on our Amazon SES account because of how much havoc this caused.  Our complaint rate skyrocketed.  Really unhappy atm.

**Comment by NicoSiebler** [comment]
Any news on this issue?

**Comment by waldok** [comment]
> Any news on this issue?

You should update mageplaza smtp extension and also install Magento patch called 'EmailMessageInterface backward compatibility issue patch for Magento 2.3.3' available from https://magento.com/tech-resources/download and should work without issues.

**Comment by NicoSiebler** [comment]
@waldok Thanks!
It's working with the SMTP module.

**Comment by SoloDevAtrix** [comment]
I finally just ran the rollback patch for email and purchased a paid extension.  Still had issues even with the rollback installed for this one (from viewing logs to weird stuff with subjects sometimes).

**Comment by Zyles** [comment]
Magento 2.3.3
Patch installed
SMTP up2date

Not working.

**Comment by dbartelmus** [comment]
> Magento 2.3.3
> Patch installed
> SMTP up2date
> 
> Not working.

Same here, have you tried @bartoll hotfix?

**Comment by NicoSiebler** [comment]
Hi.

1) We still had to apply this commit: https://github.com/magento/magento2/commit/6976aabdfdab91a9d06e412c2ed619538ed034b6
Related Issue (behaviour not limited to Outlook): https://github.com/magento/magento2/issues/25076

2) We also found that it's required to fix the default encoding from vendor/zendframework/zend-mail/src/Header/AbstractAddressList.php and that seemed to work in all places checked so far.

```bash
--- a/vendor/zendframework/zend-mail/src/Header/AbstractAddressList.php
+++ b/vendor/zendframework/zend-mail/src/Header/AbstractAddressList.php
@@ -33,7 +33,7 @@ abstract class AbstractAddressList implements HeaderInterface
      *
      * @var string
      */
-    protected $encoding = 'ASCII';
+    protected $encoding = 'UTF-8';

     /**
      * @var string lower case field name
--
2.22.0
```

At least that was a working solution in our case and could give a hint how to properly apply it with a Magento module. Be careful to test everything related if you want to try it.

**Comment by bartoll** [comment]
@dbartelmus I have had a long time break in programming, but today I have just returned :)

So I managed to check new project from scratch:
- new magento 2.3.3 installed from composer
- official magento patch applied 'EmailMessageInterface_2.3.3_backward_compatibility_composer-2019-10-30-10-20-09.patch'
- newest Mageplaza SMTP 1.2.11 installed and configured

When I run 'Send test email' I get:
1. popup error "Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for "
2. log error
<pre>
[2019-12-20 19:49:50] main.CRITICAL: Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for  {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Zend\\Mail\\Protocol\\SmtpPluginManager::get was unable to fetch or create an instance for  at /var/www/vagrant/demo1.magento.local/vendor/mageplaza/module-smtp/Mail/Transport.php:134, Zend\\ServiceManager\\Exception\\ServiceNotFoundException(code: 0): Zend\\Mail\\Protocol\\SmtpPluginManager::get was unable to fetch or create an instance for  at /var/www/vagrant/demo1.magento.local/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:555)"} []
</pre>

**Comment by Zyles** [comment]
Tried every patch for 2.3.3.

`Transaction failed: Domain contains illegal character`

**Comment by Zyles** [comment]
Okay. removing Return-Path email, now I can at least send the email but I also get garbage text in the email:

`=0A=0D=0A=0D=0A=0D=0A=0D=0A=0D=0A=0D=0A=0D=0A=`

**Comment by Arthas7895** [comment]
Currently, if you use the SMTP module (using Amazon's configuration information) and get the error 'Transaction failed: Domain contains illegal character' you can fix it in the following 2 ways
Solution 1, you can make changes to the following file (Thank you @taoufiqaitali for this solution)
https://github.com/mageplaza/magento-2-smtp/pull/203/files
Solution 2, you can remove the code || https://prnt.sc/qehred
This is change file
where have you installed SMTP\Mail\Transport.php

**Comment by dbartelmus** [comment]
@Arthas7895 thank you, after all fixes provided here, I can finally use your SMTP module again. However while test messages are send correctly, transaction emails are not - this happening only while SMTP is enabled/
The message status on the order is: "(The order confirmation email is not sent)".

How this can be related to your module?

**Comment by Condelab** [comment]
@dbartelmus 

Go to **Stores** -> **Configuration** -> **Advanced** -> **System**
Under Mail Sending Settings make sure -  **Disable Email Communications** is set to **No**.
Go to **Stores** -> **Configuration** -> **Sales** -> **Sales Emails**
Under General Settings tab, choose **Asynchronous sending** to **Disable**
Under Order tab **Enabled** to **Yes**
Now **clear/refresh your cache**.

So try to go to **Orders** and click "**Send Mail**" the email should send and the status should now be "**Email Sent**"

Hope this Helps.

**Comment by dbartelmus** [comment]
@Condelab i fix it already, after modification provided by

1. Magento official (email backward patch) and 
2. Mageplaza SMTP then I apply 
3. @bartoll fix on Mail.php to setEncoding on UTF8.

Working like new, thank you everyone.

**Comment by Zyles** [comment]
This issue has pissed me off for over a month. Thanks to retarded Magento 2 devs breaking minor releases.

I still can't get it to work. My order emails have garbage text in them  (=0D=0A=0D=0A=0D=0A=0D=). 

I have done the following:

1. Apply the Magento 2 official Email patch 
2. Apply the changes by @bartoll https://github.com/mageplaza/magento-2-smtp/issues/199#issuecomment-545191021
3. Apply the changes by @NicoSiebler https://github.com/mageplaza/magento-2-smtp/issues/199#issuecomment-567551880 https://github.com/magento/magento2/commit/6976aabdfdab91a9d06e412c2ed619538ed034b6.patch
4. Apply the patch https://github.com/mageplaza/magento-2-smtp/pull/203/files https://github.com/mageplaza/magento-2-smtp/commit/2d1e501169cdd37dabff5a7d80d1cef62d820d70.patch
5. Set Return-Path Email to empty if you are using AWS SES

This fixes the following issues I had:
1. Disposition error (Expected disposition, got)
2. Domain contains illegal character

But not the final garbage email issue.

Hope I didn't miss a step...

**Comment by Arthas7895** [comment]
@Zyles Can you check your email log and sent me a result?

**Comment by Zyles** [comment]
@Arthas7895 Not sure how to do that. Where are they stored? If you mean the email logs in admin backend, when I hit "view" they look perfectly fine, but not in Gmail.

**Comment by Zyles** [comment]
Email source says:

```
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit
```

While email from other people in my inbox says:
```
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit
```

Could this be the problem?

**Comment by Zyles** [comment]
FINALLY figured out what caused `=0D=0A=0D=0A=0D=0A=0D=` characters across the entire email.

The problem is `Mageplaza_PdfInvoice` ....

Expect a support email coming in.

**Comment by Arthas7895** [comment]
If you are using our pdf invoice module, I can confirm this is an error. I have fixed it and am in the process of updating it in the new pdf version of Invoice. You can download the patch and replace the corresponding files
[PdfInvoice (6).zip](https://github.com/mageplaza/magento-2-smtp/files/4052488/PdfInvoice.6.zip)

**Comment by Arthas7895** [comment]
We have released a new version to be compatible with Magento 2.3.3 so I will close this issue here
Thank you!

**Comment by Goeny** [comment]
@Arthas7895 
When will this update of pdf invoice be available?
We use that module aswell and experiencing the same issue. I can confirm that the .zip file above fixed the issue but need a complete release for our site.
v1.2.6 (2019-05-13) is the last one available in Mageplaza dashboard.

**Comment by Goeny** [comment]
In addition to the problems above, related to the PDF invoice module.
After installing the fix above the problem in the email is fixed.. However,... The problem still remains inside the SMTP module. 
When viewing the email logs, the strange characters are still there. And when pushing the "resend" button, the email is sent incorrect again.

**Comment by renehol** [comment]
@Arthas7895 
Is there a date ready for the new release?

**Comment by Arthas7895** [comment]
We have fixed and tested the Pdf invoice module. Currently, we are preparing to release it. The estimated time is next week.
Thank you!
